name: agroweather_guide
description: "AgroWeather Guide â€“ weather, crops, planning, and alerts for farmers."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and state
  cupertino_icons: 1.0.8
  provider: 6.1.5+1
  google_fonts: 6.3.2
  lucide_icons_flutter: 3.1.1
  fluttertoast: 9.0.0

  # Networking and location
  http: 1.5.0
  connectivity_plus: 7.0.0
  geolocator: 14.0.2
  geocoding: 2.2.2

  # Storage and notifications
  shared_preferences: 2.5.3
  flutter_local_notifications: 19.4.2
  path_provider: 2.1.5
  sqflite: 2.4.2

  # Data/time and weather
  intl: 0.20.2
  weather: 3.2.1
  fl_chart: 1.1.1
  weather_animation: 1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.9.0
  json_serializable: 6.11.1
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/data/crops.json
