name: agroweather_guide
description: "AgroWeather Guide â€“ weather, crops, planning, and alerts for farmers."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and state
  cupertino_icons: 1.0.8
  provider: 6.1.5+1
  google_fonts: 6.3.2
  lucide_icons_flutter: 3.1.1
  fluttertoast: 9.0.0

  # Networking and location
  http: 1.5.0
  connectivity_plus: 7.0.0
  geolocator: 14.0.2
  geocoding: 2.2.2

  # Storage and notifications
  shared_preferences: 2.5.3
  flutter_local_notifications: 19.4.2
  path_provider: 2.1.5
  sqflite: 2.4.2

  # Data/time and weather
  intl: ^0.19.0
  weather: 3.2.1
  fl_chart: 1.1.1
  weather_animation: 1.1.2

  # Maps and geospatial
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # AI Chatbot
  dart_openai: ^5.1.0
  dash_chat_2: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.9.0
  json_serializable: 6.11.1
  flutter_lints: 6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - lib/data/crops.json
    - lib/utils/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
